using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Infrastructure.Seeding
{
    public class SeedingConstants
    {
        // Number of seeds to be generated by Bogus seeder
        public static readonly int AccountSeedCount = 100000;
        public static readonly int StudentSeedCount = AccountSeedCount/2;
        public static readonly int EmployeeSeedCount = AccountSeedCount/2;

        // Roles constants
        public static readonly int AdminRoleId = 1;
        public static readonly int TeacherRoleId = 2;
        public static readonly int StudentRoleId = 3;

        public static readonly string AdminRoleName = "Admin";
        public static readonly string TeacherRoleName = "Teacher";
        public static readonly string StudentRoleName = "Student";
    }
}
