namespace Infrastructure.Seeding
{
    public class SeedingConstants
    {
        // Number of seeds to be generated by Bogus seeder
        public static readonly int StudentSeedCount = 100;
        public static readonly int EmployeeSeedCount = 100;

        // Roles constants
        public static readonly int AdminRoleId = 1;
        public static readonly int TeacherRoleId = 2;
        public static readonly int StudentRoleId = 3;

        public static readonly string AdminRoleName = "Admin";
        public static readonly string TeacherRoleName = "Teacher";
        public static readonly string StudentRoleName = "Student";

        // Admin account data
        public static readonly string AdminLogin = "admin";
        public static readonly string AdminEmail = "email";
        public static readonly string AdminPassword = "P@ssword1";
    }
}
