namespace Infrastructure.Seeding
{
    public class SeedingConstants
    {
        // Number of seeds to be generated by Bogus seeder
        public static readonly int StudentSeedCount = 100;
        public static readonly int EmployeeSeedCount = 100;
        public static readonly int CompanySeedCount = 100;
        public static readonly int ExternalParticipantSeedCount = 100;
        public static readonly int EventSeedCount = 100;

        // Admin account data
        public static readonly string AdminLogin = "admin";
        public static readonly string AdminEmail = "admin@example.com";
        public static readonly string AdminPassword = "P@ssword1";
    }
}
